version: '2'
services:
  telegraf:
    image: telegraf:1.18-alpine
    container_name: prjctr_telegraf
    volumes:
      - ./etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - phpsocket:/var/run
      - mysqldsocket:/var/run/mysqld
    privileged: true
    depends_on:
      - influxdb
      - prjctr_l4_mysql
      - prjctr_l4_nginx
      - prjctr_l4_php
    ports:
      - '127.0.0.1:8125:8125/udp'
  influxdb:
      image: influxdb:1.8-alpine
      container_name: prjctr_influxdb
      env_file: .env
      ports:
        - '127.0.0.1:8086:8086'
      volumes:
        - ./:/imports
        - influxdb_data:/var/lib/influxdb
  grafana:
    build:
      dockerfile: ./docker/grafana/Dockerfile
      context: .
    container_name: prjctr_grafana
    depends_on:
      - influxdb
    env_file: .env
    links:
      - influxdb
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./etc/grafana/provisioning/:/etc/grafana/provisioning/
      - ./var/lib/grafana/dashboards/:/var/lib/grafana/dashboards/
  prjctr_l4_php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    container_name: prjctr_l4_php
    ports:
      - "9000:9000"
    depends_on:
      - prjctr_l4_redis
      - prjctr_l4_mysql
    volumes:
      - ./var/www:/var/www
      - ./etc/php-fpm.d/:/usr/local/etc/php-fpm.d/
      - phpsocket:/var/run
  prjctr_l4_mysql:
    image: mysql
    container_name: prjctr_l4_mysql
    restart: always
    env_file: .env
    volumes:
      - mysqldsocket:/var/run/mysqld
    ports:
      - "127.0.0.1:3306:3306"
  prjctr_l4_redis:
    image: bitnami/redis
    container_name: prjctr_l4_redis
    env_file: .env
    ports:
      - "6379:6379"
  prjctr_l4_nginx:
    container_name: prjctr_l4_nginx
    image: nginx
    ports:
      - "80:80"
      - "8080:80"
    volumes:
      - ./var/www:/var/www/
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - phpsocket:/var/run
    depends_on:
      - prjctr_l4_php
volumes:
  grafana_data: {}
  influxdb_data: {}
  phpsocket:
  mysqldsocket: